# Paths to MAFFT utilities
hex2maffttext: /usr/lib/mafft/lib/mafft/hex2maffttext
maffttext2hex: /usr/lib/mafft/lib/mafft/maffttext2hex

# Plddt filtering parameters for models
filter: true
filter_min: 10
filter_avg: 50

astral_path: /work/FAC/FBM/DBC/cdessim2/default/dmoi/software/ASTER-Linux/bin/astral-pro
foldseek_path: foldseek
foldseek_cores: 1

custom_structs: false
cath: false

raxml_redo: false
raxml_cores: 1

submat3di: 3diphy/3DI_substmat/3di_substmat.txt
mafft_submat3di: mafftmat/3diHEXmat.txt

clean_folder: false
fam_limit: 10000

# ft2 workflow options
aaprop_csv: /work/FAC/FBM/DBC/cdessim2/default/dmoi/projects/foldtree2/foldtree2/config/aaindex1.csv

root_dir: .
ancestral: false
model: null
mafftmat: null
submat: null
outdir: null
raxml_iterations: null
n_state: null
raxmlpath: null
