name: foldtree2
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
  - bioconda
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1  # Remove or adjust if not using GPU
  - torch-geometric
  - jupyterlab
  - ipykernel
  - tqdm
  - h5py
  - pip:
      - biopython
      - einops
      - tensorboard
      - seaborn
      - py3dmol
      - e3nn
      - fair-esm
      - toytree
      - toyplot
      - polars
      - pyparsing
      - hjson
      - loguru
      - fsspec
      - huggingface-hub
      - transformers
      - lightning-utilities
      - pytorch-lightning
      - torchmetrics
      - x-transformers
      - deepspeed
      - tqdm
      - h5py
      - pandas
      - matplotlib
      - seaborn
      - scikit-learn
      - scipy
      - einops
      - tensorboard
      - py3dmol
      - e3nn
      - fair-esm
      - toytree
      - toyplot
      - polars
      - pyparsing
      - hjson
      - loguru
      - fsspec
      - huggingface-hub
      - transformers
      - lightning-utilities
      - pytorch-lightning
      - torchmetrics
      - x-transformers
      - deepspeed

# To use: conda env create -f foldtree2.yml
# To activate: conda activate foldtree2
# To launch JupyterLab: jupyter lab
